name = "PackageNursery"
uuid = "efe96826-6319-11ea-2526-2d08b851a775"
repo = "https://github.com/j-fu/PackageNursery.jl.git"
description = "Registry for packages under development"

[packages]
0714413a-66da-11ea-1294-e93a8f6a993b = { name = "NurseryTest", path = "N/NurseryTest" }
0af68cf8-b9f3-4f9e-84f2-6ecd8b7c35ba = { name = "CVFEMSystems", path = "C/CVFEMSystems" }
1015158d-cf91-42d0-8ede-00fb4817e22a = { name = "XGrid", path = "X/XGrid" }
10287013-a584-5a38-a29a-42553acd0316 = { name = "vtkfig_jll", path = "V/vtkfig_jll" }
12fb9182-3d4c-4424-8fd1-727a0899810c = { name = "ExtendableFEMBase", path = "E/ExtendableFEMBase" }
19f70b67-2887-4cf9-b19e-fe1a30c34d85 = { name = "PlutoVTKPlot", path = "P/PlutoVTKPlot" }
37660ccd-59e9-449e-8aac-be04bab01727 = { name = "ExtendableVEM", path = "E/ExtendableVEM" }
529833da-d7f1-5821-aee9-3785d4589272 = { name = "VTKMinimal_jll", path = "V/VTKMinimal_jll" }
5573ae12-3b76-41d9-b48c-81d0b6e61cc5 = { name = "GridVisualizeTools", path = "G/GridVisualizeTools" }
57876ffe-7b7d-4c51-befe-9eb7dc4baaca = { name = "PlutoCanvasPlot", path = "P/PlutoCanvasPlot" }
5a7dfd8c-b3af-4c8d-a082-d3a774d75e72 = { name = "LiquidElectrolytes", path = "L/LiquidElectrolytes" }
63b67fce-66f7-11ea-1808-1361d8c55bf4 = { name = "VTKView", path = "V/VTKView" }
6b1bba67-9fa6-466a-8c93-71aaf28c16e6 = { name = "CatmapInterface", path = "C/CatmapInterface" }
a722555e-65e0-4074-a036-ca7ce79a4aed = { name = "ExtendableFEM", path = "E/ExtendableFEM" }
c4d4532c-19f6-4375-9ced-3808a145cd37 = { name = "VoronoiFVMDiffEq", path = "V/VoronoiFVMDiffEq" }
f29f6376-6e90-4d80-80c9-fb8ec61203d5 = { name = "LessUnitful", path = "L/LessUnitful" }
fce23259-28de-47d5-8db8-ab4b90e0411e = { name = "PyDraw", path = "P/PyDraw" }
fdf3a005-71a1-4f4b-b6cc-89be6b2f2afa = { name = "TwoPointDirichletFlux", path = "T/TwoPointDirichletFlux" }
